### ISSUE TITLE
Distributing `index.js` as a json file

### ISSUE THREAD

**Issue by mominul** [wooorm/emoticon#8]
Hi!
It'd be great to have a JSON version of the `index.js` file. Recently I had to edit the `index.js` file manually to make it conform to JSON to generate a Rust crate [`emojicon`](https://github.com/mominul/emojicon). It'd help me a lot if you consider this use case.

Thanks!

**Comment by wooorm** [comment]
The goal of this module is to be useable in JavaScript. JavaScript currently does not support JSON files.

As you are building `emojicon`, you can use node/npm as a built tool and do the following on the terminal:

```sh
node -e 'import("emoticon").then(mod => console.log(JSON.stringify(mod.emoticon)))'
```

To get the JSON out.

Could you confirm whether that works for you?

**Comment by mominul** [comment]
Thanks for the tip, at least I wouldn't have to manually edit the file!

I had thought of adding this repository as a submodule and generate code by using the JSON file that this repository would provide. But as this is not feasible, I will have to use the command you have provided.

Thanks! :blush:
